import Member from '../models/Member.js';
import Book from '../models/Book.js';
import Transaction from '../models/Transaction.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import PDFDocument from 'pdfkit-table';
import { createAuditLog } from './auditController.js';

// @desc    Get report data
// ... (getReportStats remains same)
export const getReportStats = asyncHandler(async (req, res) => {
  // Log report access
  await createAuditLog(
    req.user._id,
    req.user.fullName,
    req.user.role,
    'REPORT_ACCESS',
    'Dashboard',
    `User ${req.user.fullName} (${req.user.role}) accessed Reports page`
  );

  const totalMembers = await Member.countDocuments({});
  const totalBooks = await Book.countDocuments({});
  
  const activeBorrows = await Transaction.countDocuments({
    status: { $in: ['active', 'overdue'] }
  });

  const overdueBooks = await Transaction.countDocuments({
    status: 'overdue'
  });

  // Calculate stats for this month
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

  const booksAddedThisMonth = await Book.countDocuments({
    createdAt: { $gte: startOfMonth }
  });

  const newMembersThisMonth = await Member.countDocuments({
    createdAt: { $gte: startOfMonth }
  });

  // Most popular books (top 5 by borrow count)
  const popularBooksData = await Transaction.aggregate([
    { $group: { _id: '$book', borrows: { $sum: 1 } } },
    { $sort: { borrows: -1 } },
    { $limit: 5 },
    {
      $lookup: {
        from: 'books',
        localField: '_id',
        foreignField: '_id',
        as: 'bookDetails'
      }
    },
    { $unwind: '$bookDetails' },
    {
      $project: {
        _id: 0,
        title: '$bookDetails.title',
        borrows: 1
      }
    }
  ]);

  res.json({
    totalBooks,
    totalMembers,
    activeBorrows,
    overdueBooks,
    booksAddedThisMonth,
    newMembersThisMonth,
    popularBooks: popularBooksData
  });
});

// @desc    Export report data as PDF
// @route   GET /api/reports/export/:type
// @access  Private (Admin/Librarian)
export const exportReport = asyncHandler(async (req, res) => {
  const { type } = req.params;

  // Log report download
  await createAuditLog(
    req.user._id,
    req.user.fullName,
    req.user.role,
    'REPORT_DOWNLOAD',
    type,
    `User ${req.user.fullName} (${req.user.role}) downloaded ${type} report`
  );

  const doc = new PDFDocument({ margin: 30, size: 'A4' });

  let filename = `${type.toLowerCase().replace(/\s+/g, '_')}_report.pdf`;
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
  
  doc.pipe(res);

  // Add Header
  doc.fontSize(20).text('Marlboro Library - Management System', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(16).text(`${type} Report`, { align: 'center' });
  doc.fontSize(10).text(`Generated by: ${req.user.fullName}`, { align: 'center' });
  doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()} | Time: ${new Date().toLocaleTimeString()}`, { align: 'center' });
  doc.moveDown(2);

  let tableData = {
    title: type,
    headers: [],
    rows: []
  };

  switch (type) {
    case 'Monthly Books': {
      const now = new Date();
      const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
      const books = await Book.find({ createdAt: { $gte: startOfMonth } });
      
      tableData.headers = ['Title', 'Author', 'ISBN', 'Category', 'Copies'];
      tableData.rows = books.map(b => [b.title, b.author, b.isbn, b.category, b.copies.toString()]);
      break;
    }
    case 'Members': {
      const members = await Member.find({});
      tableData.headers = ['Name', 'Email', 'Phone', 'Status', 'Joined'];
      tableData.rows = members.map(m => [
        m.name, 
        m.email, 
        m.phone, 
        m.status, 
        new Date(m.memberSince).toLocaleDateString()
      ]);
      break;
    }
    case 'Active Borrows': {
      const txs = await Transaction.find({ status: { $in: ['active', 'overdue'] } })
        .populate('member', 'name')
        .populate('book', 'title');
      
      tableData.headers = ['Member', 'Book', 'Borrow Date', 'Due Date', 'Status'];
      tableData.rows = txs.map(t => [
        t.member?.name || 'Unknown',
        t.book?.title || 'Unknown',
        new Date(t.borrowDate).toLocaleDateString(),
        new Date(t.dueDate).toLocaleDateString(),
        t.status
      ]);
      break;
    }
    case 'Overdue': {
      const txs = await Transaction.find({ status: 'overdue' })
        .populate('member', 'name')
        .populate('book', 'title');
      
      tableData.headers = ['Member', 'Book', 'Due Date', 'Fine (R)'];
      tableData.rows = txs.map(t => [
        t.member?.name || 'Unknown',
        t.book?.title || 'Unknown',
        new Date(t.dueDate).toLocaleDateString(),
        (t.fine || 0).toFixed(2)
      ]);
      break;
    }
    default:
      doc.text('Invalid report type selected.');
      doc.end();
      return;
  }

  // Draw table
  await doc.table(tableData, {
    prepareHeader: () => doc.font('Helvetica-Bold').fontSize(10),
    prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {
      doc.font('Helvetica').fontSize(10);
    },
  });

  doc.end();
});
